# CrewAI Configuration
# This file contains configuration for all crews, agents, and LLM settings

# Global LLM settings
llm:
  default_model: "gemini-2.5-flash"
  fallback_model: "gemini-1.5-flash"
  temperature: 0.7
  max_tokens: 2000
  timeout: 30
  
# Model-specific settings
models:
  gemini-2.5-flash:
    provider: "google"
    temperature: 0.7
    max_tokens: 4000
    top_p: 1.0
    thinking_budget: 0  # Disable thinking for faster responses
    
  gemini-1.5-flash:
    provider: "google"
    temperature: 0.5
    max_tokens: 2000
    top_p: 1.0
    thinking_budget: 0
    
  gemini-2.5-pro:
    provider: "google"
    temperature: 0.7
    max_tokens: 8000
    top_p: 1.0
    # Note: thinking cannot be disabled on Gemini 2.5 Pro
    
  claude-3-sonnet:
    provider: "anthropic"
    temperature: 0.7
    max_tokens: 4000
    top_p: 1.0

# Crew configurations
crews:
  research_crew:
    name: "Research Crew"
    description: "Specializes in content analysis and local experience discovery"
    process: "sequential"
    memory: true
    cache: true
    max_rpm: 10
    verbose: true
    
    agents:
      youtube_analyst:
        role: "YouTube Content Analyst"
        model: "gemini-2.5-flash"
        max_iter: 5
        allow_delegation: false
        verbose: true
        
      local_researcher:
        role: "Local Experience Researcher"
        model: "gemini-2.5-flash"
        max_iter: 3
        allow_delegation: false
        verbose: true
        
  planning_crew:
    name: "Planning Crew"
    description: "Handles route planning and itinerary creation"
    process: "sequential"
    memory: true
    cache: true
    max_rpm: 10
    verbose: true
    
    agents:
      route_planner:
        role: "Route Planning Specialist"
        model: "gemini-2.5-flash"
        max_iter: 3
        allow_delegation: false
        verbose: true
        
      itinerary_designer:
        role: "Itinerary Designer"
        model: "gemini-2.5-flash"
        max_iter: 5
        allow_delegation: false
        verbose: true
        
  content_crew:
    name: "Content Crew"
    description: "Creates podcast content and manages calendar events"
    process: "sequential"
    memory: true
    cache: true
    max_rpm: 10
    verbose: true
    
    agents:
      podcast_creator:
        role: "Podcast Content Creator"
        model: "gemini-2.5-flash"
        max_iter: 5
        allow_delegation: false
        verbose: true
        
      calendar_manager:
        role: "Calendar & Scheduling Manager"
        model: "gemini-1.5-flash"
        max_iter: 3
        allow_delegation: false
        verbose: true

# Agent backstories and personas
agent_personas:
  youtube_analyst:
    backstory: |
      You are an expert at analyzing video content and extracting meaningful insights.
      You can identify main topics, key themes, emotional context, and actionable information
      that can be used to plan real-world experiences.
    expertise: ["content analysis", "theme extraction", "audience insights"]
    personality: "analytical and detail-oriented"
    
  local_researcher:
    backstory: |
      You are a specialist in discovering local activities and experiences.
      You excel at connecting abstract themes and interests to concrete, available
      experiences in specific locations and timeframes.
    expertise: ["local knowledge", "event discovery", "experience matching"]
    personality: "curious and resourceful"
    
  route_planner:
    backstory: |
      You are an expert at route optimization and travel planning.
      You understand different transportation modes, traffic patterns, and can create
      efficient routes that maximize time and minimize travel stress.
    expertise: ["route optimization", "logistics", "transportation planning"]
    personality: "methodical and efficient"
    
  itinerary_designer:
    backstory: |
      You are a master at creating engaging itineraries that balance
      activities, travel time, and personal preferences. You understand timing,
      logistics, and how to create memorable experiences.
    expertise: ["itinerary design", "experience curation", "timing optimization"]
    personality: "creative and organized"
    
  podcast_creator:
    backstory: |
      You are a skilled podcaster and audio content creator.
      You excel at crafting compelling narratives, creating engaging scripts,
      and producing high-quality audio content that tells stories and shares experiences.
    expertise: ["storytelling", "script writing", "audio production"]
    personality: "creative and engaging"
    
  calendar_manager:
    backstory: |
      You are an expert at calendar management and scheduling coordination.
      You understand the importance of proper scheduling, reminders, and making sure
      all participants are properly informed about events and activities.
    expertise: ["scheduling", "coordination", "event management"]
    personality: "organized and reliable"

# Task configurations
task_defaults:
  max_execution_time: 300  # 5 minutes
  retry_attempts: 2
  retry_delay: 5
  context_window: 4000
  
# Flow configurations
flows:
  content_pipeline:
    name: "Content Creation Pipeline"
    max_execution_time: 1800  # 30 minutes
    parallel_execution: false
    state_persistence: true
    
  event_orchestrator:
    name: "Event Orchestrator"
    max_execution_time: 600  # 10 minutes
    parallel_execution: true
    state_persistence: false

# Memory and caching settings
memory:
  enabled: true
  provider: "short_term"  # Options: short_term, long_term, vectordb
  max_entries: 1000
  ttl: 3600  # 1 hour
  
cache:
  enabled: true
  provider: "redis"  # Options: memory, redis, file
  ttl: 1800  # 30 minutes
  max_size: 500

# Observability settings
observability:
  weave:
    enabled: true
    project_name: "crewai-mcp-pipeline"
    trace_all_agents: true
    trace_all_tasks: true
    trace_all_flows: true
    
  logging:
    level: "INFO"
    format: "json"
    include_timestamps: true
    include_agent_names: true
    
  metrics:
    enabled: true
    export_interval: 60
    include_performance: true
    include_cost_tracking: true

# Development settings
development:
  debug_mode: true
  verbose_logging: true
  save_intermediate_results: true
  mock_external_calls: false
  
# Production settings
production:
  debug_mode: false
  verbose_logging: false
  save_intermediate_results: false
  mock_external_calls: false
  performance_monitoring: true
  
# Feature toggles
features:
  enable_human_feedback: false
  enable_agent_collaboration: true
  enable_dynamic_task_assignment: false
  enable_cost_optimization: true
  enable_performance_profiling: false 