# MCP Server Configuration
# This file contains configuration for all Model Context Protocol servers

# Server endpoints and connection settings
servers:
  youtube:
    name: "YouTube MCP Server"
    endpoint: "http://localhost:8000"
    transport: "http"
    health_check: "/health"
    api_path: "/mcp/run"
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    
  exa:
    name: "Exa Search MCP Server"
    endpoint: "http://localhost:8001"
    transport: "http"
    health_check: "/health"
    api_path: "/mcp/run"
    timeout: 15
    retry_attempts: 2
    retry_delay: 0.5
    
  maps:
    name: "Maps MCP Server"
    endpoint: "http://localhost:8002"
    transport: "http"
    health_check: "/health"
    api_path: "/mcp/run"
    timeout: 20
    retry_attempts: 3
    retry_delay: 1
    
  calendar:
    name: "Calendar MCP Server"
    endpoint: "http://localhost:8003"
    transport: "http"
    health_check: "/health"
    api_path: "/mcp/run"
    timeout: 25
    retry_attempts: 2
    retry_delay: 1
    
  tts:
    name: "Text-to-Speech MCP Server"
    endpoint: "http://localhost:8004"
    transport: "http"
    health_check: "/health"
    api_path: "/mcp/run"
    timeout: 60  # TTS can take longer
    retry_attempts: 2
    retry_delay: 2

# Development environment overrides
development:
  servers:
    youtube:
      endpoint: "http://localhost:8000"
      debug: true
    exa:
      endpoint: "http://localhost:8001"
      debug: true
    maps:
      endpoint: "http://localhost:8002"
      debug: true
    calendar:
      endpoint: "http://localhost:8003"
      debug: true
    tts:
      endpoint: "http://localhost:8004"
      debug: true

# Production environment settings
production:
  servers:
    youtube:
      endpoint: "https://youtube-mcp.your-domain.com"
      ssl_verify: true
    exa:
      endpoint: "https://exa-mcp.your-domain.com"
      ssl_verify: true
    maps:
      endpoint: "https://maps-mcp.your-domain.com"
      ssl_verify: true
    calendar:
      endpoint: "https://calendar-mcp.your-domain.com"
      ssl_verify: true
    tts:
      endpoint: "https://tts-mcp.your-domain.com"
      ssl_verify: true

# Global MCP settings
global:
  connection_pool_size: 10
  max_concurrent_requests: 5
  request_timeout: 30
  enable_metrics: true
  enable_tracing: true
  log_level: "INFO"
  
# Security settings
security:
  require_authentication: false  # Set to true in production
  api_key_header: "X-MCP-API-Key"
  rate_limit:
    enabled: false
    requests_per_minute: 60
    burst_size: 10
    
# Monitoring and health checks
monitoring:
  health_check_interval: 30  # seconds
  failure_threshold: 3
  recovery_threshold: 2
  alert_webhook: null  # Set webhook URL for alerts
  
# Caching settings
caching:
  enabled: true
  ttl: 300  # 5 minutes
  max_size: 1000
  backend: "memory"  # Options: memory, redis
  
# Feature flags
features:
  enable_batch_requests: true
  enable_async_processing: true
  enable_request_compression: false
  enable_response_compression: false 