# MCP Server Configuration - Simplified for ytmcp only
# This file contains configuration for the YouTube transcript MCP server

servers:
  youtube_transcript:
    name: "YouTube Transcript MCP Server"
    transport: "stdio"
    command: "py"
    args: ["-m", "ytmcp"]
    timeout: 30
    retry_attempts: 3
    retry_delay: 1

# Global MCP settings
global:
  connection_pool_size: 10
  max_concurrent_requests: 5
  request_timeout: 30
  enable_metrics: true
  enable_tracing: false
  log_level: "INFO"
  
# Development environment
development:
  servers:
    youtube_transcript:
      debug: true

# Production environment
production:
  servers:
    youtube_transcript:
      command: "py"
      args: ["-m", "ytmcp"] 